#pragma once
#include <cstdint>
namespace logic {
enum class FlightState:uint8_t{UNKNOWN=0,BOOT,SELF_TEST,PRE_LAUNCH,PAD_SAFE,ARMED,ASCENT,APOGEE_DETECT,APOGEE_CONFIRMED,DEPLOYMENT_WAIT,PARAFOIL_STABILIZATION,GUIDED_DESCENT,FINAL_APPROACH,FLARE,LANDED,FAILSAFE_DESCENT};
inline const char* flightStateName(FlightState s){switch(s){case FlightState::UNKNOWN:return"UNKNOWN";case FlightState::BOOT:return"BOOT";case FlightState::SELF_TEST:return"SELF_TEST";case FlightState::PRE_LAUNCH:return"PRE_LAUNCH";case FlightState::PAD_SAFE:return"PAD_SAFE";case FlightState::ARMED:return"ARMED";case FlightState::ASCENT:return"ASCENT";case FlightState::APOGEE_DETECT:return"APOGEE_DETECT";case FlightState::APOGEE_CONFIRMED:return"APOGEE_CONFIRMED";case FlightState::DEPLOYMENT_WAIT:return"DEPLOYMENT_WAIT";case FlightState::PARAFOIL_STABILIZATION:return"PARAFOIL_STABILIZATION";case FlightState::GUIDED_DESCENT:return"GUIDED_DESCENT";case FlightState::FINAL_APPROACH:return"FINAL_APPROACH";case FlightState::FLARE:return"FLARE";case FlightState::LANDED:return"LANDED";case FlightState::FAILSAFE_DESCENT:return"FAILSAFE_DESCENT";}return"UNKNOWN";}
enum class GuidanceMode:uint8_t{MODE_DISABLED=0,MANUAL,HEADING_TO_TARGET,FINAL_APPROACH,FLARE,MODE_FAILSAFE};
inline const char* guidanceModeName(GuidanceMode m){switch(m){case GuidanceMode::MODE_DISABLED:return"DISABLED";case GuidanceMode::MANUAL:return"MANUAL";case GuidanceMode::HEADING_TO_TARGET:return"HEADING_TO_TARGET";case GuidanceMode::FINAL_APPROACH:return"FINAL_APPROACH";case GuidanceMode::FLARE:return"FLARE";case GuidanceMode::MODE_FAILSAFE:return"FAILSAFE";}return"UNKNOWN";}
enum class FailCode:uint8_t{FAIL_NONE=0,FAIL_IMU,FAIL_BAROMETER,FAIL_GPS_TIMEOUT,FAIL_NAV_INVALID,FAIL_SERVO,FAIL_CONTROL_LOOP,FAIL_SENSOR_DATA,FAIL_STABILIZATION_TIMEOUT,FAIL_REBOOT_UNCERTAIN,FAIL_UNKNOWN};
inline const char* failCodeName(FailCode f){switch(f){case FailCode::FAIL_NONE:return"NONE";case FailCode::FAIL_IMU:return"IMU";case FailCode::FAIL_BAROMETER:return"BAROMETER";case FailCode::FAIL_GPS_TIMEOUT:return"GPS_TIMEOUT";case FailCode::FAIL_NAV_INVALID:return"NAV_INVALID";case FailCode::FAIL_SERVO:return"SERVO";case FailCode::FAIL_CONTROL_LOOP:return"CONTROL_LOOP";case FailCode::FAIL_SENSOR_DATA:return"SENSOR_DATA";case FailCode::FAIL_STABILIZATION_TIMEOUT:return"STABILIZATION_TIMEOUT";case FailCode::FAIL_REBOOT_UNCERTAIN:return"REBOOT_UNCERTAIN";case FailCode::FAIL_UNKNOWN:return"UNKNOWN";}return"UNKNOWN";}
struct StateMachineContext{uint32_t now_ms=0;float altitude_agl_m=0,vertical_speed_mps=0,vertical_accel_mps2=0,ground_speed_mps=0,distance_to_target_m=1e9f,angular_rate_dps=0,vs_jitter_mps=0;bool gps_valid=false,baro_valid=false,imu_valid=false;uint32_t launch_confirm_ms=400,apogee_confirmation_time_ms=700,deployment_wait_ms=1500,min_stabilization_time_ms=3000,max_stabilization_time_ms=15000,landed_confirm_ms=4000,gps_loss_timeout_ms=5000;float launch_accel_mps2=8,launch_vs_mps=5,launch_alt_delta_m=10,minimum_launch_altitude_m=8,min_descent_speed_mps=1.5f,max_stabilization_gyro_rate_dps=15,stabilize_vs_jitter_mps=.75f,final_approach_altitude_m=30,final_approach_radius_m=40,flare_altitude_m=8;bool flare_enabled=false;float landed_vs_mps=1,landed_gnd_speed_mps=2,landed_angular_rate_dps=8;};
struct StateMachineRuntime{uint32_t state_entry_ms=0,condition_since_ms=0,gps_loss_since_ms=0;bool launch_seen=false,apogee_seen=false;void enter(uint32_t n){state_entry_ms=n;condition_since_ms=0;}};
struct StateMachineResult{FlightState new_state;GuidanceMode guidance_mode;FailCode fail_code;bool state_changed;};
GuidanceMode guidanceModeForState(FlightState);
StateMachineResult updateStateMachine(const StateMachineContext&,StateMachineRuntime&,FlightState,FailCode);
}
